command:
  - python
  - dash_app.py

env:
  - name: LAKEBASE_PROJECT_ID
    value: "83eb266d-27f8-4467-a7df-2b048eff09d7"
  - name: LAKEBASE_BRANCH_ID
    value: "br-shiny-math-d28d0cd4"
  - name: PGHOST
    value: "ep-hidden-haze-d2v9brhq.database.us-east-1.cloud.databricks.com"
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: PGUSER
    value: "f6e5df56-fa6c-4262-970b-8f27dd6fa850"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: PGAPPNAME
    value: "lakebase-end-to-end-training"
