command:
  - python
  - dash_app.py

env:
  - name: PGHOST
    value: "instance-6b59171b-cee8-4acc-9209-6c848ffbfbfe.database.cloud.databricks.com"
  - name: PGDATABASE
    value: "lakebasepoc"
  - name: PGUSER
    value: "token"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: PGAPPNAME
    value: "lakebase-end-to-end-training"
